#!/usr/bin/env python3
# Copyright (c) 2021 VMware, Inc.
# 
# SPDX-License-Identifier: MIT
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import getopt
import sys

import ovs.json
import ovs.db.error
import ovs.db.schema

argv0 = sys.argv[0]

def usage():
    print("""\
%(argv0)s: ovsdb schema compiler for northd
usage: %(argv0)s [OPTIONS]

The following option must be specified:
  -p, --prefix=PREFIX        Prefix for declarations in output.

The following ovsdb2ddlog options are supported:
  -f, --schema-file=FILE     OVSDB schema file.
  -o, --output-table=TABLE   Mark TABLE as output.
  --output-only-table=TABLE  Mark TABLE as output-only.  DDlog will send updates to this table directly to OVSDB without comparing it with current OVSDB state.
  --ro=TABLE.COLUMN          Ignored.
  --rw=TABLE.COLUMN          Ignored.
  --intern-table=TABLE       Ignored.
  --output-file=FILE.inc     Write output to FILE.inc. If this option is not specified, output will be written to stdout.

The following options are also available:
  -h, --help                  display this help message
  -V, --version               display version information\
""" % {'argv0': argv0})
    sys.exit(0)

if __name__ == "__main__":
    try:
        try:
            options, args = getopt.gnu_getopt(sys.argv[1:], 'p:f:o:hV',
                                              ['prefix=',
                                               'schema-file=',
                                               'output-table=',
                                               'output-only-table=',
                                               'intern-table=',
                                               'ro=',
                                               'rw=',
                                               'output-file='])
        except getopt.GetoptError as geo:
            sys.stderr.write("%s: %s\n" % (argv0, geo.msg))
            sys.exit(1)

        prefix = None
        schema_file = None
        output_tables = set()
        output_only_tables = set()
        output_file = None
        for key, value in options:
            if key in ['-h', '--help']:
                usage()
            elif key in ['-V', '--version']:
                print("ovsdb2ddlog2rust (OVN) @VERSION@")
            elif key in ['-p', '--prefix']:
                prefix = value
            elif key in ['-f', '--schema-file']:
                schema_file = value
            elif key in ['-o', '--output-table']:
                output_tables.add(value)
            elif key == '--output-only-table':
                output_only_tables.add(value)
            elif key in ['--ro', '--rw', '--intern-table']:
                pass
            elif key == '--output-file':
                output_file = value
            else:
                assert False

        if schema_file is None:
            sys.stderr.write("%s: missing -f or --schema-file option\n" % argv0)
            sys.exit(1)
        if prefix is None:
            sys.stderr.write("%s: missing -p or --prefix option\n" % argv0)
            sys.exit(1)
        if not output_tables.isdisjoint(output_only_tables):
            example = next(iter(output_tables.intersect(output_only_tables)))
            sys.stderr.write("%s: %s may not be both an output table and "
                             "an output-only table\n" % (argv0, example))
            sys.exit(1)

        schema = ovs.db.schema.DbSchema.from_json(ovs.json.from_file(
            schema_file))

        all_tables = set(schema.tables.keys())
        missing_tables = (output_tables | output_only_tables) - all_tables
        if missing_tables:
            sys.stderr.write("%s: %s is not the name of a table\n"
                             % (argv0, next(iter(missing_tables))))
            sys.exit(1)

        f = sys.stdout if output_file is None else open(output_file, "w")
        for name, tables in (
                ("input_relations", all_tables - output_only_tables),
                ("output_relations", output_tables),
                ("output_only_relations", output_only_tables)):
            f.write("pub fn %s%s() -> Vec<String> {vec![\n" % (prefix, name))
            for table in sorted(tables):
                f.write("    \"%s\".to_string(),\n" % table)
            f.write("]}\n\n")
        if schema_file is not None:
            f.close()
    except ovs.db.error.Error as e:
        sys.stderr.write("%s: %s\n" % (argv0, e))
        sys.exit(1)

# Local variables:
# mode: python
# End: